"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import type { RealtimeChannel } from "@supabase/supabase-js";
import { supabase } from "./supabaseClient";

/**
 * Table chat.
 *
 * Delivery and history are deliberately two different mechanisms:
 *
 * - **Realtime broadcast** carries the message, so it lands on everyone's
 *   screen the moment it's sent, with no replication lag and nothing to
 *   configure.
 * - **`room_messages`** stores it, so refreshing the page or joining a game
 *   in progress doesn't start you at a blank screen.
 *
 * Splitting them means chat still works if the storage half is missing —
 * an un-migrated project gets a conversation that lives for as long as the
 * tab does, rather than an error. The message id is generated by the sender
 * so both copies are the same message and a retry can't post twice.
 */

export interface ChatMessage {
  id: string;
  userId: string;
  name: string;
  body: string;
  at: number;
  /** Ours, and not yet acknowledged by the database. */
  pending?: boolean;
}

export const MAX_MESSAGE_LENGTH = 500;
/** How much backlog to pull in. A card game is not a mailing list. */
const HISTORY = 60;

interface ChatRow {
  id: string;
  user_id: string;
  name: string;
  body: string;
  created_at: string;
}

function newId(): string {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) return crypto.randomUUID();
  // Old Safari. Only needs to be unique among a table's worth of messages.
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
}

export function useRoomChat({
  code,
  userId,
  name,
  members,
}: {
  code: string | null;
  userId: string | null;
  name: string;
  /** Everyone holding a seat. Messages from anyone else are ignored. */
  members: Array<{ id: string; name: string }>;
}) {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [unread, setUnread] = useState(0);

  const channelRef = useRef<RealtimeChannel | null>(null);
  const membersRef = useRef(members);
  const readingRef = useRef(true);
  const idRef = useRef(userId);
  const nameRef = useRef(name);

  useEffect(() => {
    membersRef.current = members;
    idRef.current = userId;
    nameRef.current = name;
  });

  /**
   * Keeps the list sorted and free of duplicates, since the same message
   * arrives twice: once by broadcast and once in the stored history.
   */
  const absorb = useCallback((incoming: ChatMessage[]) => {
    if (!incoming.length) return;
    setMessages((prev) => {
      const byId = new Map(prev.map((m) => [m.id, m]));
      let changed = false;
      for (const msg of incoming) {
        const existing = byId.get(msg.id);
        const merged = { ...existing, ...msg };
        if (!existing || existing.pending !== merged.pending || existing.body !== merged.body) {
          changed = true;
        }
        byId.set(msg.id, merged);
      }
      // Re-rendering an unchanged conversation on every history reload would
      // scroll the view out from under whoever is reading it.
      if (!changed) return prev;
      return Array.from(byId.values()).sort((a, b) => a.at - b.at);
    });
  }, []);

  useEffect(() => {
    if (!code || !userId) return;
    let active = true;

    // History first, so a late joiner sees the conversation so far.
    supabase
      .from("room_messages")
      .select("id, user_id, name, body, created_at")
      .eq("code", code)
      .order("created_at", { ascending: false })
      .limit(HISTORY)
      .then(({ data }) => {
        if (!active || !data) return;
        absorb(
          (data as ChatRow[]).map((row) => ({
            id: row.id,
            userId: row.user_id,
            name: row.name,
            body: row.body,
            at: new Date(row.created_at).getTime(),
          }))
        );
      });

    const channel = supabase.channel(`chat-${code}`, { config: { broadcast: { self: false } } });
    channelRef.current = channel;

    channel.on("broadcast", { event: "message" }, (payload) => {
      if (!active) return;
      const msg = payload.payload as ChatMessage;
      if (!msg?.id || typeof msg.body !== "string") return;
      // Same rule as voice: only people at the table get to speak at it.
      if (!membersRef.current.some((m) => m.id === msg.userId)) return;
      absorb([
        {
          id: msg.id,
          userId: msg.userId,
          name: msg.name,
          body: msg.body.slice(0, MAX_MESSAGE_LENGTH),
          at: msg.at || Date.now(),
        },
      ]);
      if (!readingRef.current) setUnread((n) => n + 1);
    });

    channel.subscribe();

    return () => {
      active = false;
      channelRef.current = null;
      void supabase.removeChannel(channel);
    };
  }, [code, userId, absorb]);

  const send = useCallback(
    async (raw: string) => {
      const body = raw.trim().slice(0, MAX_MESSAGE_LENGTH);
      const me = idRef.current;
      if (!body || !code || !me) return;

      const message: ChatMessage = {
        id: newId(),
        userId: me,
        name: nameRef.current,
        body,
        at: Date.now(),
      };

      // Show it immediately, send it outward, then store it. The order
      // matters: the table is the slowest of the three and the least
      // important for the conversation feeling live.
      absorb([{ ...message, pending: true }]);

      void channelRef.current?.send({ type: "broadcast", event: "message", payload: message });

      const { error: saveError } = await supabase.from("room_messages").insert({
        id: message.id,
        code,
        user_id: me,
        name: message.name,
        body: message.body,
      });

      // A message that sent but didn't store is fine — everyone saw it, it
      // just won't survive a refresh. Not worth an error in their face.
      absorb([{ ...message, pending: false }]);
      if (saveError && process.env.NODE_ENV === "development") {
        console.warn("chat history not saved:", saveError.message);
      }
    },
    [code, absorb]
  );

  /** Call when the chat is on screen, so the badge reflects reality. */
  const markRead = useCallback((reading: boolean) => {
    readingRef.current = reading;
    if (reading) setUnread(0);
  }, []);

  return { messages, unread, send, markRead };
}
